export enum DamageTypes {
    Bludgeoning = "Bludgeoning",
    Piercing = "Piercing",
    Slashing = "Slashing",
    Fire = "Fire",
    Cold = "Cold",
    Acid = "Acid",
    Thunder = "Thunder",
    Lightning = "Lightning",
    Poison = "Poison",
    Radiant = "Radiant",
    Necrotic = "Necrotic",
    Psychic = "Psychic",
    Force = "Force",
}